name: Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_push:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    name: Build/Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: birdiecare
          password: ${{ secrets.GH_REGISTRY_TOKEN}}
      - name: Build/Push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/birdiecare/helm-eks-image:${{ github.sha }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: birdiecare
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Extract image tag name
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Retag image with release tag
        run: |
          docker pull ghcr.io/birdiecare/helm-eks-image:$GITHUB_SHA
          docker tag ghcr.io/birdiecare/helm-eks-image:$GITHUB_SHA ghcr.io/birdiecare/helm-eks-image:$RELEASE_TAG
          docker push ghcr.io/birdiecare/helm-eks-image:$RELEASE_TAG
