name: Publish Docker image

on:
  push:
    branches:
      - main
      - build-for-github
      - gh-workflows
    tags:
      - '*.*.*'

env:
  NEW_IMAGE_TAG: ${{ startsWith(github.ref, 'refs/tags/') && ${GITHUB_REF#refs/tags/} || github.sha }}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      # - name: Extract image tag
      #   run: |
      #     echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: context
        run: |
          echo "$NEW_IMAGE_TAG"
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: birdiecare
      #     password: ${{ secrets.GH_REGISTRY_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: |
      #       ghcr.io/birdiecare/helm-eks-image:${{ env.IMAGE_TAG }}
